Fix crash in single record draw optimization
PaintOpBuffer's RasterWithAlpha crashes when used on ops that are not
draw ops.  The code that tries to recursively apply this
optimization to single op records did not check whether that op is
a draw op or not and so this would crash.

The last unit test crashes before this patch and passes after.  The
other unit tests are there just to fill out more related unit tests.

An alternative to this approach would be to just make it possible for all ops
to support RasterWithAlpha, but that'd be extra code gen that in
practice wouldn't ever get used.

Bug: 712093
Change-Id: I5358d99a85891f180c49576745ee95294097fdbf

diff --git a/third_party/closure_compiler/roll_closure_compiler b/third_party/closure_compiler/roll_closure_compiler
--- a/third_party/closure_compiler/roll_closure_compiler
+++ b/third_party/closure_compiler/roll_closure_compiler
@@ -5,18 +5,11 @@
 #
 # Download the newest version of Closure Compiler, build it and put into Chrome
 # source tree. Also update externs/chrome_extensions.js.
-
-java -version 2>&1 | head -1 | egrep -q '\b1\.7'
-if [[ $? -ne 0 ]]; then
-  echo "This script requires Java 1.7" >&2
-  exit 1
-fi
-
-javac -version 2>&1 | egrep -q '\b1\.7'
-if [[ $? -ne 0 ]]; then
-  echo "This script requires JDK 1.7" >&2
-  exit 1
-fi
+#
+# TODO(dbeam): we don't really need to build the compiler any more. We used to
+# need to because we built a custom runner. We could probably just curl
+# https://dl.google.com/closure-compiler/compiler-latest.zip and unzip. And get
+# the externs from rawgit.com.
 
 readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 readonly TEMP_DIR=$(mktemp -d)
@@ -58,8 +51,28 @@ EOT
 )
 fi
 
+check_jdk_version() {
+  # Pretty contrived checks modeling how we write Maven XML files.
+  if [ ! -r "$2" ]; then
+    echo "Could not find $2" >&2
+    exit 1
+  elif ! fgrep -q '<jdk.version>'$1'</jdk.version>' "$2"; then
+    echo "JDK version $1 must be specified in $2" >&2
+    exit 1
+  elif ! fgrep -q '<source>${jdk.version}</source>' "$2"; then
+    echo "Java source must be specified to be \${jdk.version} in $2" >&2
+    exit 1
+  elif ! fgrep -q '<target>${jdk.version}</target>' "$2"; then
+    echo "Java target must be specified to be \${jdk.version} in $2" >&2
+    exit 1
+  fi
+}
+
+echo "Checking JDK Version Used to Build"
+check_jdk_version 1.7 pom.xml
+
 echo "Building Closure Compiler"
-mvn install -DskipTests=true --projects com.google.javascript:closure-compiler
+mvn clean install -DskipTests=true --projects com.google.javascript:closure-compiler,com.google.javascript:closure-compiler-externs
 
 if [[ "$?" -ne 0 ]]; then
   echo "Failed to build jar, copying nothing" >&2
@@ -67,18 +80,8 @@ if [[ "$?" -ne 0 ]]; then
   exit 1
 fi
 
-# TODO(dbeam): this .jar seems to be a bit bigger than the jar previously built
-# by ant. I tried many other jars in target/, but none of them were able to
-# build the runner.jar without issue.
+# TODO(dbeam): the Maven-built jar seems a little bigger than the ant version.
 cp target/closure-compiler-1.0-SNAPSHOT.jar "${SCRIPT_DIR}/compiler/compiler.jar"
-
-echo "Re-building runner.jar"
-"${SCRIPT_DIR}/runner/build_runner_jar.py"
-if [[ "$?" -ne 0 ]]; then
-  echo "Failed to build runner.jar, roll unsuccessful"
-  cleanup
-  exit 1
-fi
 
 readonly WARNING="$(cat <<EOT
 //    SSSSSSSSSSSSSSS TTTTTTTTTTTTTTTTTTTTTTT     OOOOOOOOO     PPPPPPPPPPPPPPPPP
